from enum import Enum


class Permission(str, Enum):
    MANAGE_USERS = "MANAGE_USERS"
    VIEW_REPORTS = "VIEW_REPORTS"
    EDIT_TEMPLATES = "EDIT_TEMPLATES"
    LOAD_FILES = "LOAD_FILES"
    GENERATE_DUA = "GENERATE_DUA"
    DOWNLOAD_DUA = "DOWNLOAD_DUA"
